# Generated by Django 4.2.11 on 2024-04-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coffee_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('description', models.TextField()),
                ('cnpj', models.CharField(max_length=100)),
                ('allow_reservation', models.BooleanField(default=False)),
                ('reservation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coffee_spotlight', models.CharField(max_length=100)),
                ('internet_speed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vegan_options', models.BooleanField(default=False)),
                ('zero_lactose_options', models.BooleanField(default=False)),
                ('gluten_free_options', models.BooleanField(default=False)),
                ('acessibility', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
            ],
        ),
    ]
