# Generated by Django 5.0.4 on 2024-06-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
