# Generated by Django 5.0.3 on 2024-06-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_reservation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee_shop',
            name='has_meeting_room',
            field=models.BooleanField(default=False),
        ),
    ]
