# Generated by Django 5.0.3 on 2024-06-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_coffee_shop_has_meeting_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee_shop',
            name='has_silent_environment',
            field=models.BooleanField(default=False),
        ),
    ]
