# Generated by Django 5.0.3 on 2024-06-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_coffee_shop_has_silent_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee_shop',
            name='zip_code',
            field=models.CharField(default='00000-000', max_length=15),
        ),
    ]
