# Generated by Django 5.0.3 on 2024-06-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_coffee_shop_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee_shop',
            name='instagram',
            field=models.CharField(default='@coffice', max_length=100),
        ),
        migrations.AddField(
            model_name='coffee_shop',
            name='phone',
            field=models.CharField(default='(00) 0000-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='coffee_shop',
            name='site_url',
            field=models.URLField(default='https://coffice.com.br', max_length=100),
        ),
    ]
