# Generated by Django 5.0.4 on 2024-06-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_coffee_shop_instagram_coffee_shop_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee_shop',
            name='alone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coffee_shop',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
