# Generated by Django 5.0.4 on 2024-06-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_coffee_shop_alone_coffee_shop_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee_shop',
            name='group',
        ),
    ]
